services:
  db_dev:
    image: postgres:latest
    env_file:
      - .env.development
    ports:
      - "5432:5432"
    networks:
      - shadyfile_network

networks:
  shadyfile_network:
    name: shadyfile_network
