services:
  db_dev:
    image: postgres:latest
    env_file:
      - .env.development
    ports:
      - "5434:5432"
    restart: unless-stopped
    networks:
      - shadyfile_network

networks:
  shadyfile_network:
    name: shadyfile_network
